receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  resource: # Resource spec https://opentelemetry.io/docs/specs/semconv/resource/
    attributes:
      - action: insert
        key: loki.format
        value: raw
      - action: insert
        key: loki.resource.labels
        value: service.name, app, runtime
  
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  telemetry:  # Collector telemetry
    metrics:
      address: 0.0.0.0:8888

  prometheus: # metrics
    endpoint: "0.0.0.0:8889"
    # namespace: demo
    send_timestamps: true
    resource_to_telemetry_conversion:
      enabled: true
    # const_labels:
    #   exported: "collector"
  
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  
  otlphttp/loki:
    # endpoint: http://loki:3100/loki/api/v1/push
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true
  
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ prometheus, debug ]
    
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp/tempo, debug ]
    
    logs:
      receivers: [ otlp ]
      processors: [ batch, resource ]
      exporters: [ otlphttp/loki, debug ]